import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const FIXTURES = resolve(process.cwd(), "../tests/fixtures/format_snapshots");
const OUT = resolve(process.cwd(), "src/types/api.ts");

type Json = unknown;

function zodFor(value: Json, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (value === null) return "z.null()";
  if (Array.isArray(value)) {
    return value.length === 0
      ? "z.array(z.unknown())"
      : `z.array(${zodFor(value[0], indent)})`;
  }
  if (typeof value === "object") {
    const obj = value as Record<string, Json>;
    const lines = Object.entries(obj).map(
      ([key, val]) => `${pad}  ${JSON.stringify(key)}: ${zodFor(val, indent + 1)},`,
    );
    return `z.object({\n${lines.join("\n")}\n${pad}})`;
  }
  if (typeof value === "string") return "z.string()";
  if (typeof value === "number") return "z.number()";
  if (typeof value === "boolean") return "z.boolean()";
  return "z.unknown()";
}

function pascalCase(name: string): string {
  return name.replace(/(^|[-_])(.)/g, (_m, _sep, chr: string) =>
    chr.toUpperCase(),
  );
}

const lines: string[] = [
  "// AUTOGENERATED by web/scripts/gen-types.ts. Do not edit by hand.",
  "// Run `npm run gen-types` after changing tests/fixtures/format_snapshots/*.",
  "",
  'import { z } from "zod";',
  "",
];

for (const file of readdirSync(FIXTURES).filter((f) => f.endsWith(".json"))) {
  const base = file.replace(/\.json$/, "");
  const name = pascalCase(base);
  const data = JSON.parse(readFileSync(join(FIXTURES, file), "utf8"));
  lines.push(`export const ${name}Schema = ${zodFor(data)};`);
  lines.push(`export type ${name} = z.infer<typeof ${name}Schema>;`);
  lines.push("");
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`wrote ${OUT}`);
