// AUTOGENERATED by web/scripts/gen-types.ts. Do not edit by hand.
// Run `npm run gen-types` after changing tests/fixtures/format_snapshots/*.
//
// The generator merges shapes across array entries and emits zod unions when
// a property is observed with multiple kinds (e.g. `string | null`). For
// fields that are nullable at runtime but only have `null` observations in
// every fixture, the resulting schema will be `z.null()`. Add a non-null
// observation in a fixture array entry to widen the schema.

import { z } from "zod";

export const FailuresSchema = z.array(z.object({
  "blame_scope": z.string(),
  "category": z.string(),
  "confidence": z.number(),
  "evidence": z.array(z.string()),
  "recoverability": z.string(),
  "run_id": z.string(),
  "severity": z.string(),
  "source": z.string(),
  "summary": z.string(),
  "workspace_id": z.string(),
}));
export type Failures = z.infer<typeof FailuresSchema>;

export const LatestSchema = z.object({
  "agent_mode": z.string(),
  "agent_name": z.string(),
  "agent_outcome": z.string(),
  "display_title": z.null(),
  "ended_at": z.string(),
  "eval_status": z.string(),
  "import_state": z.null(),
  "parent_run_id": z.null(),
  "recording_mode": z.string(),
  "residual_risks": z.array(z.unknown()),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "status": z.string(),
  "usage": z.null(),
  "workspace_id": z.string(),
});
export type Latest = z.infer<typeof LatestSchema>;

export const LatestImportedSchema = z.object({
  "agent_mode": z.string(),
  "agent_name": z.string(),
  "agent_outcome": z.string(),
  "display_title": z.string(),
  "ended_at": z.string(),
  "eval_status": z.string(),
  "import_state": z.string(),
  "parent_run_id": z.null(),
  "recording_mode": z.string(),
  "residual_risks": z.array(z.unknown()),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "status": z.string(),
  "usage": z.object({
    "input_tokens": z.number(),
    "output_tokens": z.number(),
    "cache_creation_tokens": z.number(),
    "cache_read_tokens": z.number(),
    "reasoning_tokens": z.number(),
    "cost_usd": z.number(),
    "pricing_source": z.string(),
    "confidence": z.string(),
    "model_breakdown": z.array(z.object({
      "model": z.string(),
      "input_tokens": z.number(),
      "output_tokens": z.number(),
      "cache_creation_tokens": z.number(),
      "cache_read_tokens": z.number(),
      "reasoning_tokens": z.number(),
    })),
  }),
  "workspace_id": z.string(),
});
export type LatestImported = z.infer<typeof LatestImportedSchema>;

export const RisksSchema = z.array(z.object({
  "category": z.string(),
  "run_id": z.string(),
  "severity": z.string(),
  "source": z.string(),
  "summary": z.string(),
  "workspace_id": z.string(),
}));
export type Risks = z.infer<typeof RisksSchema>;

export const ShowSchema = z.object({
  "agent": z.string(),
  "agent_outcome": z.string(),
  "display_title": z.null(),
  "eval_status": z.string(),
  "failures": z.array(z.object({
    "blame_scope": z.string(),
    "category": z.string(),
    "confidence": z.number(),
    "evidence": z.array(z.string()),
    "recoverability": z.string(),
    "run_id": z.string(),
    "severity": z.string(),
    "source": z.string(),
    "summary": z.string(),
    "workspace_id": z.string(),
  })),
  "import_state": z.null(),
  "risks": z.array(z.object({
    "category": z.string(),
    "run_id": z.string(),
    "severity": z.string(),
    "source": z.string(),
    "summary": z.string(),
    "workspace_id": z.string(),
  })),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "usage": z.null(),
  "workspace_id": z.string(),
  "workspace_short": z.string(),
});
export type Show = z.infer<typeof ShowSchema>;

export const ShowImportedSchema = z.object({
  "agent": z.string(),
  "agent_outcome": z.string(),
  "display_title": z.string(),
  "eval_status": z.string(),
  "failures": z.array(z.unknown()),
  "import_state": z.string(),
  "risks": z.array(z.unknown()),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "usage": z.object({
    "input_tokens": z.number(),
    "output_tokens": z.number(),
    "cache_creation_tokens": z.number(),
    "cache_read_tokens": z.number(),
    "reasoning_tokens": z.number(),
    "cost_usd": z.number(),
    "pricing_source": z.string(),
    "confidence": z.string(),
    "model_breakdown": z.array(z.object({
      "model": z.string(),
      "input_tokens": z.number(),
      "output_tokens": z.number(),
      "cache_creation_tokens": z.number(),
      "cache_read_tokens": z.number(),
      "reasoning_tokens": z.number(),
    })),
  }),
  "workspace_id": z.string(),
  "workspace_short": z.string(),
});
export type ShowImported = z.infer<typeof ShowImportedSchema>;

export const StatusSchema = z.array(z.object({
  "agent_mode": z.string(),
  "agent_name": z.string(),
  "agent_outcome": z.string(),
  "display_title": z.null(),
  "ended_at": z.string(),
  "eval_status": z.string(),
  "import_state": z.null(),
  "parent_run_id": z.null(),
  "recording_mode": z.string(),
  "residual_risks": z.array(z.object({
    "severity": z.string(),
    "summary": z.string(),
  })),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "status": z.string(),
  "usage": z.null(),
  "workspace_id": z.string(),
}));
export type Status = z.infer<typeof StatusSchema>;

export const StatusImportedSchema = z.array(z.object({
  "agent_mode": z.string(),
  "agent_name": z.string(),
  "agent_outcome": z.string(),
  "display_title": z.union([z.null(), z.string()]),
  "ended_at": z.string(),
  "eval_status": z.string(),
  "import_state": z.union([z.null(), z.string()]),
  "parent_run_id": z.null(),
  "recording_mode": z.string(),
  "residual_risks": z.array(z.unknown()),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "status": z.string(),
  "usage": z.union([z.null(), z.object({
    "input_tokens": z.number(),
    "output_tokens": z.number(),
    "cache_creation_tokens": z.number(),
    "cache_read_tokens": z.number(),
    "reasoning_tokens": z.number(),
    "cost_usd": z.number(),
    "pricing_source": z.string(),
    "confidence": z.string(),
    "model_breakdown": z.array(z.object({
      "model": z.string(),
      "input_tokens": z.number(),
      "output_tokens": z.number(),
      "cache_creation_tokens": z.number(),
      "cache_read_tokens": z.number(),
      "reasoning_tokens": z.number(),
    })),
  })]),
  "workspace_id": z.string(),
}));
export type StatusImported = z.infer<typeof StatusImportedSchema>;
