import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const FIXTURES = resolve(process.cwd(), "../tests/fixtures/format_snapshots");
const OUT = resolve(process.cwd(), "src/types/api.ts");

type Json = unknown;

// Type tag captured per observation. Across array entries the generator
// merges shapes by accumulating observations per object property; when a
// property is observed with multiple kinds (e.g. `string` and `null`) the
// emitter produces `z.union([T, z.null()])`. Recursive shapes (arrays,
// objects) merge structurally so nested unions surface too.
type TypeNode =
  | { kind: "null" }
  | { kind: "string" }
  | { kind: "number" }
  | { kind: "boolean" }
  | { kind: "unknown" }
  | { kind: "array"; element: TypeNode }
  | { kind: "object"; props: Map<string, TypeNode[]> };

function classify(value: Json): TypeNode {
  if (value === null) return { kind: "null" };
  if (Array.isArray(value)) {
    if (value.length === 0) return { kind: "array", element: { kind: "unknown" } };
    const merged = value.map(classify).reduce(unifyArrayElement);
    return { kind: "array", element: merged };
  }
  if (typeof value === "object") {
    const props = new Map<string, TypeNode[]>();
    for (const [k, v] of Object.entries(value as Record<string, Json>)) {
      props.set(k, [classify(v)]);
    }
    return { kind: "object", props };
  }
  if (typeof value === "string") return { kind: "string" };
  if (typeof value === "number") return { kind: "number" };
  if (typeof value === "boolean") return { kind: "boolean" };
  return { kind: "unknown" };
}

function unifyArrayElement(a: TypeNode, b: TypeNode): TypeNode {
  if (a.kind === "object" && b.kind === "object") {
    const props = new Map<string, TypeNode[]>(a.props);
    for (const [k, vs] of b.props) {
      const existing = props.get(k) ?? [];
      props.set(k, [...existing, ...vs]);
    }
    return { kind: "object", props };
  }
  if (a.kind === "array" && b.kind === "array") {
    return { kind: "array", element: unifyArrayElement(a.element, b.element) };
  }
  // Primitives that disagree across array entries surface via the property
  // merge above. The reducer here only needs to keep one canonical shape; the
  // disagreement at primitive level becomes a per-property union when objects
  // contain it.
  return a;
}

function emit(node: TypeNode, indent = 0): string {
  const pad = "  ".repeat(indent);
  switch (node.kind) {
    case "null":
      return "z.null()";
    case "string":
      return "z.string()";
    case "number":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "unknown":
      return "z.unknown()";
    case "array":
      return `z.array(${emit(node.element, indent)})`;
    case "object": {
      const lines = [...node.props.entries()].map(([key, accs]) => {
        const observed = collapse(accs);
        const first = observed[0];
        if (!first) {
          return `${pad}  ${JSON.stringify(key)}: z.unknown(),`;
        }
        const inner =
          observed.length === 1
            ? emit(first, indent + 1)
            : `z.union([${observed.map((n) => emit(n, indent + 1)).join(", ")}])`;
        return `${pad}  ${JSON.stringify(key)}: ${inner},`;
      });
      return `z.object({\n${lines.join("\n")}\n${pad}})`;
    }
  }
}

function collapse(nodes: TypeNode[]): TypeNode[] {
  // Reduce a list of observed TypeNodes for a single property into the
  // smallest set we'd emit as a union. Same-kind observations merge
  // structurally; different kinds remain as separate union members.
  const out: TypeNode[] = [];
  for (const n of nodes) {
    const idx = out.findIndex((o) => o.kind === n.kind);
    if (idx === -1) {
      out.push(n);
      continue;
    }
    const existing = out[idx];
    if (!existing) continue;
    out[idx] = unifyArrayElement(existing, n);
  }
  return out;
}

function pascalCase(name: string): string {
  return name.replace(/(^|[-_])(.)/g, (_m, _sep, chr: string) =>
    chr.toUpperCase(),
  );
}

const lines: string[] = [
  "// AUTOGENERATED by web/scripts/gen-types.ts. Do not edit by hand.",
  "// Run `npm run gen-types` after changing tests/fixtures/format_snapshots/*.",
  "//",
  "// The generator merges shapes across array entries and emits zod unions when",
  "// a property is observed with multiple kinds (e.g. `string | null`). For",
  "// fields that are nullable at runtime but only have `null` observations in",
  "// every fixture, the resulting schema will be `z.null()`. Add a non-null",
  "// observation in a fixture array entry to widen the schema.",
  "",
  'import { z } from "zod";',
  "",
];

for (const file of readdirSync(FIXTURES).filter((f) => f.endsWith(".json"))) {
  const base = file.replace(/\.json$/, "");
  const name = pascalCase(base);
  const data = JSON.parse(readFileSync(join(FIXTURES, file), "utf8"));
  const node = classify(data);
  lines.push(`export const ${name}Schema = ${emit(node)};`);
  lines.push(`export type ${name} = z.infer<typeof ${name}Schema>;`);
  lines.push("");
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`wrote ${OUT}`);
