// AUTOGENERATED by web/scripts/gen-types.ts. Do not edit by hand.
// Run `npm run gen-types` after changing tests/fixtures/format_snapshots/*.

import { z } from "zod";

export const FailuresSchema = z.array(z.object({
  "blame_scope": z.string(),
  "category": z.string(),
  "confidence": z.number(),
  "evidence": z.array(z.string()),
  "recoverability": z.string(),
  "run_id": z.string(),
  "severity": z.string(),
  "source": z.string(),
  "summary": z.string(),
  "workspace_id": z.string(),
}));
export type Failures = z.infer<typeof FailuresSchema>;

export const LatestSchema = z.object({
  "agent_mode": z.string(),
  "agent_name": z.string(),
  "agent_outcome": z.string(),
  "ended_at": z.string(),
  "eval_status": z.string(),
  "parent_run_id": z.null(),
  "recording_mode": z.string(),
  "residual_risks": z.array(z.unknown()),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "status": z.string(),
  "workspace_id": z.string(),
});
export type Latest = z.infer<typeof LatestSchema>;

export const RisksSchema = z.array(z.object({
  "category": z.string(),
  "run_id": z.string(),
  "severity": z.string(),
  "source": z.string(),
  "summary": z.string(),
  "workspace_id": z.string(),
}));
export type Risks = z.infer<typeof RisksSchema>;

export const ShowSchema = z.object({
  "agent": z.string(),
  "agent_outcome": z.string(),
  "eval_status": z.string(),
  "failures": z.array(z.object({
    "blame_scope": z.string(),
    "category": z.string(),
    "confidence": z.number(),
    "evidence": z.array(z.string()),
    "recoverability": z.string(),
    "run_id": z.string(),
    "severity": z.string(),
    "source": z.string(),
    "summary": z.string(),
    "workspace_id": z.string(),
  })),
  "risks": z.array(z.object({
    "category": z.string(),
    "run_id": z.string(),
    "severity": z.string(),
    "source": z.string(),
    "summary": z.string(),
    "workspace_id": z.string(),
  })),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "workspace_id": z.string(),
  "workspace_short": z.string(),
});
export type Show = z.infer<typeof ShowSchema>;

export const StatusSchema = z.array(z.object({
  "agent_mode": z.string(),
  "agent_name": z.string(),
  "agent_outcome": z.string(),
  "ended_at": z.string(),
  "eval_status": z.string(),
  "parent_run_id": z.null(),
  "recording_mode": z.string(),
  "residual_risks": z.array(z.object({
    "severity": z.string(),
    "summary": z.string(),
  })),
  "run_id": z.string(),
  "sealed_phase": z.string(),
  "started_at": z.string(),
  "status": z.string(),
  "workspace_id": z.string(),
}));
export type Status = z.infer<typeof StatusSchema>;
